apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ensat-app.local # Add this to your /etc/hosts or hosts file
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ensat-laravel-service
            port:
              number: 80
